mappings = {
  # af (1/73)
  'INKASSIE': 'INBOX',
  'ASBLIK': 'TRASH',
  'BELANGRIK': 'IMPORTANT',
  'GESTER': 'STARRED',
  'GESTUURDE E-POS': 'SENT',
  'KONSEPTE': 'DRAFT',
  'STROOIPOS': 'SPAM',
  # az (2/73)
  'GƏLƏNLƏR': 'INBOX',
  'GÖNDƏRILƏNLƏR': 'SENT',
  'QARALAMALAR': 'DRAFT',
  'ULDUZLU': 'STARRED',
  'ZIBIL QUTUSU': 'TRASH',
  'ÖNƏMLI': 'IMPORTANT',
  # id (3/73)
  'KOTAK MASUK': 'INBOX',
  'BERBINTANG': 'STARRED',
  'DRAF': 'DRAFT',
  'PENTING': 'IMPORTANT',
  'SURAT TERKIRIM': 'SENT',
  'TONG SAMPAH': 'TRASH',
  # ms (4/73)
  'PETI MASUK': 'INBOX',
  'DIBINTANGKAN': 'STARRED',
  'DRAF': 'DRAFT',
  'MEL DIHANTAR': 'SENT',
  'PENTING': 'IMPORTANT',
  'SAMPAH': 'TRASH',
  # ca (5/73)
  'SAFATA D’ENTRADA': 'INBOX',
  'CORREU BROSSA': 'SPAM',
  'ENVIATS': 'SENT',
  'ESBORRANYS': 'DRAFT',
  'IMPORTANTS': 'IMPORTANT',
  'MISSATGES DESTACATS': 'STARRED',
  'PAPERERA': 'TRASH',
  # cs (6/73)
  'DORUČENÁ POŠTA': 'INBOX',
  'DŮLEŽITÉ': 'IMPORTANT',
  'KONCEPTY': 'DRAFT',
  'KOŠ': 'TRASH',
  'ODESLANÁ POŠTA': 'SENT',
  'S HVĚZDIČKOU': 'STARRED',
  # cy (7/73)
  'BLWCH DERBYN': 'INBOX',
  'BIN SBWRIEL': 'TRASH',
  'DRAFFT': 'DRAFT',
  'E-BOST SOTHACH': 'SPAM',
  'NEGESEUON A ANFONWYD': 'SENT',
  'PWYSIG': 'IMPORTANT',
  'SERENNOG': 'STARRED',
  # da (8/73)
  'INDBAKKE': 'INBOX',
  'KLADDER': 'DRAFT',
  'PAPIRKURV': 'TRASH',
  'SENDTE MAILS': 'SENT',
  'STJERNEMARKEREDE': 'STARRED',
  'VIGTIGT': 'IMPORTANT',
  # de (9/73)
  'POSTEINGANG': 'INBOX',
  'ENTWÜRFE': 'DRAFT',
  'GESENDET': 'SENT',
  'MARKIERT': 'STARRED',
  'PAPIERKORB': 'TRASH',
  'WICHTIG': 'IMPORTANT',
  # et (10/73)
  'POSTKAST': 'INBOX',
  'MUSTANDID': 'DRAFT',
  'OLULINE': 'IMPORTANT',
  'PRÜGIKAST': 'TRASH',
  'RÄMPSPOST': 'SPAM',
  'SAADETUD KIRJAD': 'SENT',
  'TÄRNIGA': 'STARRED',
  # en-GB (11/73)
  'BIN': 'TRASH',
  'DRAFTS': 'DRAFT',
  'SENT MAIL': 'SENT',
  # en (12/73)
  'DRAFTS': 'DRAFT',
  'SENT MAIL': 'SENT',
  # es (13/73)
  'RECIBIDOS': 'INBOX',
  'BORRADORES': 'DRAFT',
  'DESTACADOS': 'STARRED',
  'ENVIADOS': 'SENT',
  'IMPORTANTES': 'IMPORTANT',
  'PAPELERA': 'TRASH',
  # es-419 (14/73)
  'RECIBIDOS': 'INBOX',
  'BORRADORES': 'DRAFT',
  'DESTACADOS': 'STARRED',
  'ENVIADOS': 'SENT',
  'IMPORTANTES': 'IMPORTANT',
  'PAPELERA': 'TRASH',
  # eu (15/73)
  'SARRERA-ONTZIA': 'INBOX',
  'BIDALITAKO MEZUAK': 'SENT',
  'GARRANTZITSUAK': 'IMPORTANT',
  'IZARDUNAK': 'STARRED',
  'SPAMA': 'SPAM',
  'ZABORRONTZIA': 'TRASH',
  'ZIRRIBORROAK': 'DRAFT',
  # fil (16/73)
  'MAHALAGA': 'IMPORTANT',
  'MAY-BITUIN': 'STARRED',
  'MGA DRAFT': 'DRAFT',
  'NAIPADALANG SULAT': 'SENT',
  # fr (17/73)
  'BOÎTE DE RÉCEPTION': 'INBOX',
  'BROUILLONS': 'DRAFT',
  'CORBEILLE': 'TRASH',
  'MESSAGES ENVOYÉS': 'SENT',
  'SUIVIS': 'STARRED',
  # fr-CA (18/73)
  'BOÎTE DE RÉCEPTION': 'INBOX',
  'BROUILLONS': 'DRAFT',
  'CORBEILLE': 'TRASH',
  'FAVORIS': 'STARRED',
  'IMPORTANTS': 'IMPORTANT',
  'MESSAGES ENVOYÉS': 'SENT',
  'POURRIEL': 'SPAM',
  # ga (19/73)
  'BOSCA ISTEACH': 'INBOX',
  'BRUSCAR': 'TRASH',
  'DRÉACHTAÍ': 'DRAFT',
  'LE RÉILTÍN': 'STARRED',
  'SEOLTA': 'SENT',
  'TURSCAR': 'SPAM',
  'TÁBHACHTACH': 'IMPORTANT',
  # gl (20/73)
  'CAIXA DE ENTRADA': 'INBOX',
  'BORRADORES': 'DRAFT',
  'CAIXA DA PAPELEIRA': 'TRASH',
  'CORREO ENVIADO': 'SENT',
  'IMPORTANTES': 'IMPORTANT',
  'MARCADO CON ESTRELA': 'STARRED',
  # hr (21/73)
  'PRISTIGLA POŠTA': 'INBOX',
  'NEŽELJENA POŠTA': 'SPAM',
  'OTPAD': 'TRASH',
  'POSLANA POŠTA': 'SENT',
  'SA ZVJEZDICOM': 'STARRED',
  'SKICE': 'DRAFT',
  'VAŽNO': 'IMPORTANT',
  # it (22/73)
  'POSTA IN ARRIVO': 'INBOX',
  'BOZZE': 'DRAFT',
  'CESTINO': 'TRASH',
  'IMPORTANTI': 'IMPORTANT',
  'POSTA INVIATA': 'SENT',
  'SPECIALI': 'STARRED',
  # zu (23/73)
  'IBHOKISI LOKUNGENAYO': 'INBOX',
  'IMEYILI ETHUNYELWE': 'SENT',
  'OKUBALULEKILE': 'IMPORTANT',
  'OKUNENKANYEZI': 'STARRED',
  'OKUNGAPHELELE': 'DRAFT',
  'UDOTI': 'TRASH',
  'UGAXEKILE': 'SPAM',
  # is (24/73)
  'PÓSTHÓLF': 'INBOX',
  'DRÖG': 'DRAFT',
  'MIKILVÆGT': 'IMPORTANT',
  'RUSL': 'TRASH',
  'RUSLPÓSTUR': 'SPAM',
  'SENDUR PÓSTUR': 'SENT',
  'STJÖRNUMERKT': 'STARRED',
  # sw (25/73)
  'KIKASHA': 'INBOX',
  'BARUA ZILIZOTUMWA': 'SENT',
  'BARUA TAKA': 'SPAM',
  'MUHIMU': 'IMPORTANT',
  'RASIMU': 'DRAFT',
  'TUPIO': 'TRASH',
  'ZENYE NYOTA': 'STARRED',
  # lv (26/73)
  'IESŪTNE': 'INBOX',
  'AR ZVAIGZNĪTI': 'STARRED',
  'MELNRAKSTI': 'DRAFT',
  'MISKASTE': 'TRASH',
  'MĒSTULES': 'SPAM',
  'NOSŪTNE': 'SENT',
  'SVARĪGI': 'IMPORTANT',
  # lt (27/73)
  'GAUTIEJI': 'INBOX',
  'IŠSIŲSTI LAIŠKAI': 'SENT',
  'JUODRAŠČIAI': 'DRAFT',
  'PAŽYMĖTI ŽVAIGŽDUTE': 'STARRED',
  'SVARBU': 'IMPORTANT',
  'ŠIUKŠLIADĖŽĖ': 'TRASH',
  'ŠLAMŠTAS': 'SPAM',
  # hu (28/73)
  'GAUTIEJI': 'INBOX',
  'IŠSIŲSTI LAIŠKAI': 'SENT',
  'JUODRAŠČIAI': 'DRAFT',
  'PAŽYMĖTI ŽVAIGŽDUTE': 'STARRED',
  'SVARBU': 'IMPORTANT',
  'ŠIUKŠLIADĖŽĖ': 'TRASH',
  'ŠLAMŠTAS': 'SPAM',
  # no (29/73)
  'INNBOKS': 'INBOX',
  'PAPIRKURV': 'TRASH',
  'SENDT E-POST': 'SENT',
  'STJERNEMERKET': 'STARRED',
  'SØPPELPOST': 'SPAM',
  'UTKAST': 'DRAFT',
  'VIKTIG': 'IMPORTANT',
  # nl (30/73)
  'BELANGRIJK': 'IMPORTANT',
  'CONCEPTEN': 'DRAFT',
  'MET STER': 'STARRED',
  'PRULLENBAK': 'TRASH',
  'VERZONDEN BERICHTEN': 'SENT',
  # pl (31/73)
  'ODEBRANE': 'INBOX',
  'KOSZ': 'TRASH',
  'OZNACZONE GWIAZDKĄ': 'STARRED',
  'WAŻNE': 'IMPORTANT',
  'WERSJE ROBOCZE': 'DRAFT',
  'WYSŁANE': 'SENT',
  # pt-BR (32/73)
  'CAIXA DE ENTRADA': 'INBOX',
  'COM ESTRELA': 'STARRED',
  'E-MAILS ENVIADOS': 'SENT',
  'IMPORTANTE': 'IMPORTANT',
  'LIXEIRA': 'TRASH',
  'RASCUNHOS': 'DRAFT',
  # pt-PT (33/73)
  'CAIXA DE ENTRADA': 'INBOX',
  'CAIXOTE DO LIXO': 'TRASH',
  'COM ESTRELA': 'STARRED',
  'CORREIO ENVIADO': 'SENT',
  'IMPORTANTE': 'IMPORTANT',
  'RASCUNHOS': 'DRAFT',
  # ro (34/73)
  'MESAJE PRIMITE': 'INBOX',
  'COȘ DE GUNOI': 'TRASH',
  'IMPORTANTE': 'IMPORTANT',
  'MESAJE IMPORTANTE': 'STARRED',
  'MESAJE NEFINALIZATE': 'DRAFT',
  'MESAJE TRIMISE': 'SENT',
  # sk (35/73)
  'DORUČENÉ': 'INBOX',
  'DÔLEŽITÉ': 'IMPORTANT',
  'KÔŠ': 'TRASH',
  'ODOSLANÉ': 'SENT',
  'ROZPÍSANÉ SPRÁVY': 'DRAFT',
  'S HVIEZDIČKOU': 'STARRED',
  # sl (36/73)
  'PREJETO': 'INBOX',
  'OSNUTKI': 'DRAFT',
  'POMEMBNO': 'IMPORTANT',
  'POSLANO': 'SENT',
  'SMETNJAK': 'TRASH',
  'VSILJENA POŠTA': 'SPAM',
  'Z ZVEZDICO': 'STARRED',
  # fi (37/73)
  'POSTILAATIKKO': 'INBOX',
  'LUONNOKSET': 'DRAFT',
  'LÄHETETYT VIESTIT': 'SENT',
  'ROSKAKORI': 'TRASH',
  'ROSKAPOSTI': 'SPAM',
  'TÄHDELLÄ MERKITYT': 'STARRED',
  'TÄRKEÄÄ': 'IMPORTANT',
  # sv (38/73)
  'INKORGEN': 'INBOX',
  'PAPPERSKORGEN': 'TRASH',
  'SKICKAT': 'SENT',
  'SKRÄPPOST': 'SPAM',
  'STJÄRNMÄRKTA': 'STARRED',
  'UTKAST': 'DRAFT',
  'VIKTIGT': 'IMPORTANT',
  # vi (39/73)
  'HỘP THƯ ĐẾN': 'INBOX',
  'QUAN TRỌNG': 'IMPORTANT',
  'THÙNG RÁC': 'TRASH',
  'THƯ GẮN DẤU SAO': 'STARRED',
  'THƯ NHÁP': 'DRAFT',
  'THƯ ĐÃ GỬI': 'SENT',
  # tr (40/73)
  'GELEN KUTUSU': 'INBOX',
  'GÖNDERILMIŞ POSTALAR': 'SENT',
  'TASLAKLAR': 'DRAFT',
  'YILDIZLI': 'STARRED',
  'ÇÖP KUTUSU': 'TRASH',
  'ÖNEMLI': 'IMPORTANT',
  # el (41/73)
  'ΑΝΕΠΙΘΎΜΗΤΑ': 'SPAM',
  'ΑΠΕΣΤΑΛΜΈΝΑ': 'SENT',
  'ΚΆΔΟΣ ΑΠΟΡΡΙΜΜΆΤΩΝ': 'TRASH',
  'ΜΕ ΑΣΤΈΡΙ': 'STARRED',
  'ΠΡΌΧΕΙΡΑ': 'DRAFT',
  'ΣΗΜΑΝΤΙΚΆ': 'IMPORTANT',
  'ΕΙΣΕΡΧΌΜΕΝΑ': 'INBOX',
  # bg (42/73)
  'ВАЖНО': 'IMPORTANT',
  'ИЗПРАТЕНИ': 'SENT',
  'КОШЧЕ': 'TRASH',
  'СПАМ': 'SPAM',
  'СЪС ЗВЕЗДА': 'STARRED',
  'ЧЕРНОВИ': 'DRAFT',
  'ВХ. ПОЩА': 'INBOX',
  # mn (43/73)
  'ИЛГЭЭСЭН ИМЭЙЛ': 'SENT',
  'НООРГУУД': 'DRAFT',
  'ОДТОЙ': 'STARRED',
  'СПАМ': 'SPAM',
  'ХОГИЙН САВ': 'TRASH',
  'ЧУХАЛ': 'IMPORTANT',
  'ИРСЭН ИМЭЙЛ': 'INBOX',
  # ru (44/73)
  'ВАЖНОЕ': 'IMPORTANT',
  'КОРЗИНА': 'TRASH',
  'ОТПРАВЛЕННЫЕ': 'SENT',
  'ПОМЕЧЕННЫЕ': 'STARRED',
  'СПАМ': 'SPAM',
  'ЧЕРНОВИКИ': 'DRAFT',
  'ВХОДЯЩИЕ': 'INBOX',
  # sr (45/73)
  'ВАЖНО': 'IMPORTANT',
  'НЕДОВРШЕНЕ': 'DRAFT',
  'НЕПОЖЕЉНЕ': 'SPAM',
  'ОТПАД': 'TRASH',
  'ПОСЛАТЕ': 'SENT',
  'СА ЗВЕЗДИЦОМ': 'STARRED',
  'ПРИМЉЕНЕ': 'INBOX',
  # uk (46/73)
  'ІЗ ЗІРОЧКОЮ': 'STARRED',
  'ВАЖЛИВО': 'IMPORTANT',
  'КОШИК': 'TRASH',
  'НАДІСЛАНІ': 'SENT',
  'СПАМ': 'SPAM',
  'ЧЕРНЕТКИ': 'DRAFT',
  'ВХІДНІ': 'INBOX',
  # hy (47/73)
  'ԱՂԲԱՐԿՂ': 'TRASH',
  'ԱՍՏՂԱՆՇՎԱԾ': 'STARRED',
  'ԿԱՐԵՒՈՐ': 'IMPORTANT',
  'ՈՒՂԱՐԿՎԱԾ': 'SENT',
  'ՍՊԱՄ': 'SPAM',
  'ՍԵՒԱԳՐԵՐ': 'DRAFT',
  'ՄՈՒՏՔԻ ԱՐԿՂ': 'INBOX',
  # he (48/73)
  'אשפה': 'TRASH',
  'דואר יוצא': 'SENT',
  'חשוב': 'IMPORTANT',
  'טיוטות': 'DRAFT',
  'מסומן בכוכב': 'STARRED',
  'ספאם': 'SPAM',
  'דואר נכנס': 'INBOX',
  # ur (49/73)
  'اہم': 'IMPORTANT',
  'بھیجے گئے پیغامات': 'SENT',
  'ستارے کے نشان والے': 'STARRED',
  'سپام': 'SPAM',
  'مسودہ س': 'DRAFT',
  'کوڑے کی ٹوکری': 'TRASH',
  'موصول شدہ پیغامات': 'INBOX',
  # ar (50/73)
  'الرسائل المميزة بنجمة': 'STARRED',
  'الرسائل غير المرغوب فيها': 'SPAM',
  'المهـملات': 'TRASH',
  'بريد مرسل': 'SENT',
  'مسودّات': 'DRAFT',
  'مهم': 'IMPORTANT',
  'البريد الوارد': 'INBOX',
  # fa (51/73)
  'حذف‌شده‌ها': 'TRASH',
  'ستاره‌دار': 'STARRED',
  'مهم': 'IMPORTANT',
  'نامه‌های فرستاده شده': 'SENT',
  'هرزنامه': 'SPAM',
  'پیش‌نویس‌ها': 'DRAFT',
  'صندوق ورودی': 'INBOX',
  # ne (52/73)
  'ड्राफ्ट': 'DRAFT',
  'ताराङ्कित': 'STARRED',
  'पठाइएको मेल': 'SENT',
  'महत्त्वपूर्ण': 'IMPORTANT',
  'रद्दी टोकरी': 'TRASH',
  'स्प्याम': 'SPAM',
  'इनबक्स': 'INBOX',
  # mr (53/73)
  'तारांकित': 'STARRED',
  'पाठवलेले मेल': 'SENT',
  'मसुदे': 'DRAFT',
  'महत्त्वाचे': 'IMPORTANT',
  'वगळलेले': 'TRASH',
  'स्पॅम': 'SPAM',
  'इनबॉक्स': 'INBOX',
  # hi (54/73)
  'अधूरा ईमेल': 'DRAFT',
  'अनचाहा': 'SPAM',
  'कूड़ेदान': 'TRASH',
  'भेजी गई मेल': 'SENT',
  'महत्वपूर्ण': 'IMPORTANT',
  'स्टार के निशान वाला': 'STARRED',
  'इनबॉक्स': 'INBOX',
  # bn (55/73)
  'গুরুত্বপূর্ণ': 'IMPORTANT',
  'ট্র্যাশ': 'TRASH',
  'ড্রাফ্ট': 'DRAFT',
  'তারকাচিহ্নিত': 'STARRED',
  'প্রেরিত মেল': 'SENT',
  'স্প্যাম': 'SPAM',
  'ইনবক্স': 'INBOX',
  # gu (56/73)
  'ટ્રેશ': 'TRASH',
  'ડ્રાફ્ટ્સ': 'DRAFT',
  'તારાંકિત': 'STARRED',
  'મહત્વપૂર્ણ': 'IMPORTANT',
  'મોકલેલા મેઇલ': 'SENT',
  'સ્પામ': 'SPAM',
  'ઇનબોકસ': 'INBOX',
  # ta (57/73)
  'அனுப்பிய அஞ்சல்': 'SENT',
  'நட்சத்திரமிட்டது': 'STARRED',
  'நீக்கப்பட்டவை': 'TRASH',
  'முக்கியமானவை': 'IMPORTANT',
  'வரைவுகள்': 'DRAFT',
  'ஸ்பேம்': 'SPAM',
  'இன்பாக்ஸ்': 'INBOX',
  # te (58/73)
  'చిత్తుప్రతులు': 'DRAFT',
  'ట్రాష్': 'TRASH',
  'నక్షత్రం గుర్తుతో': 'STARRED',
  'పంపిన సందేశాలు': 'SENT',
  'ముఖ్యమైన': 'IMPORTANT',
  'స్పామ్': 'SPAM',
  'ఇన్‌‌బాక్స్‌': 'INBOX',
  # kn (59/73)
  'ಅನುಪಯುಕ್ತ': 'TRASH',
  'ಕಳುಹಿಸಿದ ಮೇಲ್': 'SENT',
  'ಡ್ರಾಫ್ಟ್‌ಗಳು': 'DRAFT',
  'ನಕ್ಷತ್ರ ಹಾಕಿದ': 'STARRED',
  'ಪ್ರಮುಖ': 'IMPORTANT',
  'ಸ್ಪ್ಯಾಮ್': 'SPAM',
  'ಇನ್‌ಬಾಕ್ಸ್': 'INBOX',
  # ml (60/73)
  'അയച്ച മെയിൽ‍': 'SENT',
  'ട്രാഷ്': 'TRASH',
  'ഡ്രാഫ്‌റ്റുകൾ‍': 'DRAFT',
  'നക്ഷത്രമിട്ടവ': 'STARRED',
  'പ്രധാനപ്പെട്ടവ': 'IMPORTANT',
  'സ്പാം': 'SPAM',
  'ഇൻബോക്സ്': 'INBOX',
  # si (61/73)
  'අපද්‍රව්‍ය': 'TRASH',
  'අයාචිත තැපෑල': 'SPAM',
  'කටු සටහන්': 'DRAFT',
  'තරු ලකුණු කළ': 'STARRED',
  'යැවූ ලිපි': 'SENT',
  'වැදගත්': 'IMPORTANT',
  'එන ලිපි': 'INBOX',
  # th (62/73)
  'จดหมายขยะ': 'SPAM',
  'จดหมายที่ส่งแล้ว': 'SENT',
  'ติดดาว': 'STARRED',
  'ถังขยะ': 'TRASH',
  'ร่างจดหมาย': 'DRAFT',
  'สำคัญ': 'IMPORTANT',
  'กล่องจดหมาย': 'INBOX',
  # lo (63/73)
  'ຈົດໝາຍທີ່ສົ່ງແລ້ວ': 'SENT',
  'ຕິດດາວ': 'STARRED',
  'ຖັງຂີ້ເຫຍື້ອ': 'TRASH',
  'ສະບັບຮ່າງ': 'DRAFT',
  'ສະແປມ': 'SPAM',
  'ສຳຄັນ': 'IMPORTANT',
  'ອິນບັອກ': 'INBOX',
  # my (64/73)
  'စတားတပ်ထားသော': 'STARRED',
  'စပမ်း': 'SPAM',
  'ထွက်စာ': 'SENT',
  'မူကြမ်းများ': 'DRAFT',
  'အမှိုက်ပုံး': 'TRASH',
  'အရေးကြီး': 'IMPORTANT',
  'ဝင်စာ': 'INBOX',
  # ka (65/73)
  'ᲒᲐᲒᲖᲐᲕᲜᲘᲚᲔᲑᲘ': 'SENT',
  'ᲕᲐᲠᲡᲙᲕᲚᲐᲕᲘᲐᲜᲘ': 'STARRED',
  'ᲛᲜᲘᲨᲕᲜᲔᲚᲝᲕᲐᲜᲘ': 'IMPORTANT',
  'ᲛᲝᲜᲐᲮᲐᲖᲔᲑᲘ': 'DRAFT',
  'ᲡᲞᲐᲛᲘ': 'SPAM',
  'ᲬᲐᲨᲚᲘᲚᲔᲑᲘ': 'TRASH',
  'ᲨᲔᲛᲝᲡᲣᲚᲔᲑᲘ.': 'INBOX',
  # am (66/73)
  'ረቂቆች': 'DRAFT',
  'አስፈላጊ': 'IMPORTANT',
  'አይፈለጌ መልዕክት': 'SPAM',
  'ኮከብ የተደረገባቸው': 'STARRED',
  'የተላከ ኢሜይል': 'SENT',
  'ጣል': 'TRASH',
  'የገቢ መልዕክት ሳጥን': 'INBOX',
  # chr (67/73)
  'ᎢᎬᏱ ᎪᏪᎸᏅ': 'DRAFT',
  'ᎤᎵᏍᎨᏓ': 'IMPORTANT',
  'ᎤᏲ': 'TRASH',
  'ᎤᏲᎢ': 'SPAM',
  'ᏃᏈᏏ ᎪᏪᎳᏅᎯ': 'STARRED',
  'ᏫᎦᏅᏅᎯ ᎪᏪᎸ': 'SENT',
  'ᎧᏁᏌᎢᏱ': 'INBOX',
  # km (68/73)
  'ធុងសំរាម': 'TRASH',
  'បានដាក់ផ្កាយ': 'STARRED',
  'សេចក្ដី​ព្រាង': 'DRAFT',
  'សំខាន់': 'IMPORTANT',
  'អ៊ីមែល​​បាន​ផ្ញើ': 'SENT',
  '​សារ​ឥត​បានការ': 'SPAM',
  'ប្រអប់ទទួល': 'INBOX',
  # zh-HK (69/73)
  '垃圾桶': 'TRASH',
  '垃圾郵件': 'SPAM',
  '寄件備份': 'SENT',
  '已加星號': 'STARRED',
  '草稿': 'DRAFT',
  '重要郵件': 'IMPORTANT',
  '收件箱': 'INBOX',
  # zh-CN (70/73)
  '垃圾邮件': 'SPAM',
  '已删除邮件': 'TRASH',
  '已加星标': 'STARRED',
  '已发邮件': 'SENT',
  '草稿': 'DRAFT',
  '重要': 'IMPORTANT',
  '收件箱': 'INBOX',
  # zh-TW (71/73)
  '垃圾桶': 'TRASH',
  '垃圾郵件': 'SPAM',
  '寄件備份': 'SENT',
  '已加星號': 'STARRED',
  '草稿': 'DRAFT',
  '重要郵件': 'IMPORTANT',
  '收件匣': 'INBOX',
  # ja (72/73)
  'ゴミ箱': 'TRASH',
  'スター付き': 'STARRED',
  '下書き': 'DRAFT',
  '迷惑メール': 'SPAM',
  '送信済みメール': 'SENT',
  '重要': 'IMPORTANT',
  '受信トレイ': 'INBOX',
  # ko (73/73)
  '별표편지함': 'STARRED',
  '보낸편지함': 'SENT',
  '스팸함': 'SPAM',
  '임시보관함': 'DRAFT',
  '중요': 'IMPORTANT',
  '휴지통': 'TRASH',
  '받은편지함': 'INBOX',
}